name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A concise description of what the bug is.
#       placeholder: Tell us what you see!
#       value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: false   
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you using?
      options:
        - 0.3.1 (Default)
        - 0.3.0
        - 0.2.1
        - 0.2.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  - type: dropdown
    id: severity_1
    attributes:
      label: Severity
#       description: What version are you using?
      options:
        - 1 - Critical Function Down
        - 2 - Critical Function Impaired
        - 3 - Group Productivity Impaired
        - 4 - Individual Productivity Impaired
        - 5 - Productivity not immediately affected
    validations:
      required: true
