name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-outcome
    attributes:
      label: Describe the expected outcome
#       description: A concise description of .
#       placeholder: Tell us what you see!
#       value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: actual-outcome
    attributes:
      label: Describe the actual outcome
#       description: A concise description of what the bug is.
#       placeholder: Tell us what you see!
#       value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: false   
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you using?
      options:
        - 0.3.1 (Default)
        - 0.3.0
        - 0.2.1
        - 0.2.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  - type: checkboxes
    id: help-used
    attributes:
      label: Have you tried the following?
#       description: You may select more than one.
      options:
        - label: Check the [Troubleshooting section](https://github.com/cert-manager/aws-privateca-issuer#troubleshooting)
        - label: Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best fits the issue. Please refer [Categories of Issues](https://github.com/solonish/test/blob/main/docs/issue-categories.md) for more details.
      options:
        - Authentication Issue
        - Supported Workflow Broken
        - Build Issues
        - Broken Testing Infrastructure
        - Incorrect Documentation
        - Other
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Assgin a severity level to this issue. Please refer [Severity of Issues](https://github.com/solonish/test/blob/main/docs/severity.md) for more details.
      options:
        - Severity 1
        - Severity 2
        - Severity 3
        - Severity 4
    validations:
      required: False
