blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url: ../#troubleshooting
    about: Check the basic troubleshooting steps here
  - name: Search open issues
    url: https://github.com/cert-manager/aws-privateca-issuer/issues
    about: Check for any open issues or Known Issue announcements
  - name: Slack Channel
    url: https://kubernetes.slack.com
    about: Ask question on our slack channel
